title: Chezter Vargas
description: Biomedical engineer. Hobbyist programmer. PC Gamer.
baseurl: ""
url: "https://lecaseus.github.io"
github_username: LeCaseus
linkedin_username: lecaseus
repo_url: "https://github.com/LeCaseus/LeCaseus.github.io"

collections:
  projects:
    output: true
    permalink: /projects/:name/

permalink: /readings/:year/:month/:day/:title/

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md